### ISSUE TITLE
Location: Unrecognized location type near

### ISSUE THREAD

**Issue by mkewan** [SciStarter/Circuit#100]
There are several SciStarter opps with locations showing as "Unrecognized location type near" 

E.g. https://beta.sciencenearme.org/plastic-pirates-go-europe-1 
https://beta.sciencenearme.org/rhs-cellar-slug-survey
https://beta.sciencenearme.org/monitoring-at-water-and-feed-stations-post-bushfire-1

![image](https://user-images.githubusercontent.com/93145199/139698204-4b7b24c7-1338-41d8-9e4c-5b7e097a774e.png)

**Comment by SciStarter** [comment]
Fixed.
