### ISSUE TITLE
My Science error

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#109]
When logged in, I saw the number 4 on my "My Science" tab in navigation, so when I clicked on it it said an error occurred.

![Screenshot 2021-11-08 105012](https://user-images.githubusercontent.com/92173479/140773954-12f70024-3caa-477d-9c75-65a823cd9ca5.png)

**Comment by SciStarter** [comment]
This happened because I had removed all of the SciStarter opportunities and was in the middle of reloading them.
