### ISSUE TITLE
Opportunity error

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#110]
https://beta.sciencenearme.org/mozak-brainbuilder brings up this blank page, when logged in only.

![Screenshot 2021-11-08 105316](https://user-images.githubusercontent.com/92173479/140774258-f458ccff-eaa0-4c56-afbd-8e2608080768.png)

**Comment by SciStarter** [comment]
Works now. This was likely related to the reload of SciStarter opportunities as well.
