### ISSUE TITLE
Provider icon

### ISSUE THREAD

**Issue by adamfagen** [SciStarter/Circuit#116]
It would be helpful to have a required square icon for the host/provider or some other way to scale in the opportunity list. Some that are significantly rectangular (e.g., Catawba Science Center) render confusingly.

![image](https://user-images.githubusercontent.com/94076731/141180622-e3c84946-1643-412e-b557-51ebbd8212c4.png)

**Comment by SciStarter** [comment]
I'd like this handled in the front-end rendering, if we can.

**Comment by kevinripka-uiowa** [comment]
Best I can do is change fitting the image to being contained. Already did it and it's on beta.
