### ISSUE TITLE
social media buttons

### ISSUE THREAD

**Issue by Ycitsci** [SciStarter/Circuit#12]
6. How about adding more key social media, like Pinterest, instagram, Whatsapp and Snapchat for convenient sharing? Also, it'll be great if all social media logos share the same button shape (eg. round-cornered).
![6 social buttons](https://user-images.githubusercontent.com/92533858/137410644-e7d91adc-54be-4a88-a7b6-347d35bf6bf3.png)

**Comment by kevinripka-uiowa** [comment]
I don't think we need more than the ones we had. We talked about this and decided on these 3.
