### ISSUE TITLE
icon for project's topic/categorization

### ISSUE THREAD

**Issue by Ycitsci** [SciStarter/Circuit#13]
7. On the individual project page, can the icon for showing the categorization/topic of a project be changed to something that looks like a tag. Now the icon looks like one for conversations/forum.
![7 old tag icon](https://user-images.githubusercontent.com/92533858/137410828-03b1db96-577e-4f5d-9a50-e173651fadd4.png)

suggested icon:
![7 new tag icon](https://user-images.githubusercontent.com/92533858/137410832-cc378a8c-e217-4092-adce-e36f903cd6bd.png)

**Comment by kevinripka-uiowa** [comment]
@Ycitsci Well, the topic is what's being talked about, so that's why I selected that. But it's not a big deal to change.
@SciStarter more important, can we have it as user words and not underscores?

**Comment by kevinripka-uiowa** [comment]
changed. in front-end-refactor
