### ISSUE TITLE
Remove "science" from navigation tabs when logged in

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#135]
Kevin - Darlene and I just checked in, and she expressed that she thinks the word "science" is redundant in the navigation tabs when logged in.  Plus it reinforces a science-only approach which we're trying to stay away from.  

She'd like us to remove the word "Science" and update these to:

- Find Opportunities
- Saved Opportunities
- My Activity Log  (including changing the shopping bag icon to a clipboard icon, and updating the first tab in this view "Report Your Science" to "Report Your Activities"

![Screenshot 2021-11-15 104343](https://user-images.githubusercontent.com/92173479/141810941-9f7d6193-a63e-4572-8be1-0ad8d5976baa.png)

**Comment by jbskolnik** [comment]
Also I see that "Saved Science Opportunities" seems to have a smaller indent than the rest of the navigation links.

**Comment by kevinripka-uiowa** [comment]
fixed in front-end-refactor
