### ISSUE TITLE
Link colors looking different

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#137]
Not sure why some of the links are darker blue vs. teal, and some underlined and some not?

![Screenshot 2021-11-15 112103](https://user-images.githubusercontent.com/92173479/141816986-ff4b776d-15d2-4b19-b796-be4fa8440ee9.png)

**Comment by kevinripka-uiowa** [comment]
@jbskolnik This looks like you fixed it? The best I can guess is cutting and pasting from a styled document. I see a bunch here set as a font that isn't are font. I'll try to put in some overrides. But maybe you can paste without style. I know most software you do that with command+shift+v. But, you might have to paste first into a plain text document.

**Comment by kevinripka-uiowa** [comment]
Put in overrides that should work.
