### ISSUE TITLE
Live Site - couldn't get location

### ISSUE THREAD

**Issue by kevinripka-uiowa** [SciStarter/Circuit#146]
I just went to the live site (not beta) and allowed location, but it never got my location. The here and now just stayed loading. Then I tried adding my location (iowa city, ia) and used the autocomplete to select it, hit search, and I got an error page. The url it went to was https://www.sciencenearme.org/find?physical=in-person-or-online&beginning=2021-11-30T00%3A00%3A00.000Z&sort=closest so it seems like it's ignoring location entirely.

**Comment by Ycitsci** [comment]
I allowed SNM to get my location, but it seems the site doesn't. 
![Screen Shot 2021-12-16 at 10 51 12](https://user-images.githubusercontent.com/92533858/146405724-a3f66e26-78ce-4929-8a21-8c7fd14a58fc.png)



I used the URL Kevin posted, the autofill location field shows Iowa City, IA, but not my location. 
![Screen Shot 2021-12-16 at 10 59 38](https://user-images.githubusercontent.com/92533858/146405743-eaffb13e-48f1-4f74-8e57-e3e5baf9ab79.png)
