### ISSUE TITLE
error message on lots of pages and "return to home page" link not working

### ISSUE THREAD

**Issue by darcav1** [SciStarter/Circuit#149]
this was sent to us from a user: "I clicked on a Facebook link that took me to your site. I am using an iPad.
Autofill entered my location as Rockville, and I left the first box blank to see all science events within ten miles of me. The initial date was today, and the ending date box was blank.

My result was the page in the attached picture. When I clicked on the link to return to the home page, it sent me back to the same error page.

Sincerely,
Quinn Finkel"
![snm screenshot](https://user-images.githubusercontent.com/34452244/144160619-c512654f-edba-43a0-b24b-bb6bfa781fe6.jpg)

**Comment by Ycitsci** [comment]
Tried the same query. Can't reproduce this issue, or it looks fixed. 
![snm search 3](https://user-images.githubusercontent.com/92533858/146403568-677c6c18-1d9b-4fb0-ae4a-135400a7252a.png)
