### ISSUE TITLE
Wrong location for Washington Sea Grant State of the Oyster

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#152]
Location is ", Washington, US" and shows up in a search for DC for 25 miles and map is DC, but looks like the project is Washington State?

https://sciencenearme.org/state-of-the-oyster

![Screenshot 2021-12-01 094953](https://user-images.githubusercontent.com/92173479/144256376-9efd5b45-6a3a-4a9f-b973-b8ff9c9cbb01.png)

**Comment by SciStarter** [comment]
That's a data issue. I'll look into the SciStarter record to see what's up.
