### ISSUE TITLE
Once logged in, the "log out" unfolds right away

### ISSUE THREAD

**Issue by Ycitsci** [SciStarter/Circuit#154]
Once user is logged in, they'll see the screen below, with the "log out" option seeable right away. On a regular laptop screen, the "log out" option blocks part of other information nearby. 
Can the log out option be folded once user is logged in?
<img width="1326" alt="once logged in" src="https://user-images.githubusercontent.com/92533858/144269137-faf84ea4-15b9-4755-a132-ef280b1642e6.png">

**Comment by kevinripka-uiowa** [comment]
fixed
