### ISSUE TITLE
"Site blocked from locations..."

### ISSUE THREAD

**Issue by darcav1** [SciStarter/Circuit#157]
<img width="304" alt="Screen Shot 2021-12-01 at 2 12 54 PM" src="https://user-images.githubusercontent.com/34452244/144298700-bac0616e-8edf-441c-bd79-b41b1a9f64ce.png">

https://sciencenearme.org/find?proximity=40233&beginning=2021-12-01T00%3A00%3A00.000Z&sort=closest

**Comment by SciStarter** [comment]
That's a user-controlled device setting.
