### ISSUE TITLE
Search brings up error message and can't go home

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#158]
Martin tried searching on the homepage not logged on for astronomy near new york, and then he gets this screen:  

![Screenshot 2021-12-01 141226](https://user-images.githubusercontent.com/92173479/144298871-5a785bd9-8282-441c-bc1a-8a8a4919e53f.png)

**Comment by Ycitsci** [comment]
Used the same and different search queries not logged in. The results look good. 
![snm search1](https://user-images.githubusercontent.com/92533858/146401919-8301ab9c-19de-4600-92b0-a0167f90d9bc.png)
![snm search2](https://user-images.githubusercontent.com/92533858/146401921-0a0632c1-5e43-4601-abd7-29ab252e8937.png)

**Comment by SciStarter** [comment]
Yes, this is fixed.
