### ISSUE TITLE
Hard to see search options on mobile

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#159]
When I go to the site on mobile with Chrome, and click on the search button, it brings up results without showing me what I searched for.  Is there a way to show the search criteria plus the results, like we have on the desktop view?

![Screenshot_20211201-142022](https://user-images.githubusercontent.com/92173479/144299836-1f602147-8263-4b64-9c13-b8b5aa939fe3.png)

**Comment by kevinripka-uiowa** [comment]
@jbskolnik @SciStarter this isn't working as expected. That should bring up a search form. Somewhere in all the change this got messed up. Have to look into it more.

**Comment by kevinripka-uiowa** [comment]
changes made. should be good now.
