### ISSUE TITLE
Location not clearing properly for search

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#161]
Here's the URL: https://sciencenearme.org/find?physical=in-person-or-online&beginning=2021-12-10T00%3A00%3A00.000Z&sort=closest&partner_text&descriptor_text&topic_text&text&near=Lower%20Makefield%20Township,%20PA%2019067,%20United%20States&longitude=-74.8383245&latitude=40.2132492&proximity=80467&page=0&descriptors%5B%5D=festival

![Screenshot 2021-12-10 122217](https://user-images.githubusercontent.com/92173479/145615516-6d7ef7e4-c87a-411b-83ef-037d08af10e5.png)

**Comment by SciStarter** [comment]
Fixed
