### ISSUE TITLE
Make Research Participant Link on footer

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#163]
Please add to the footer a link to https://sciencenearme.org/research-participant. Also change link in the cookies modal to linking to this new page, not informed consent.

**Comment by SciStarter** [comment]
Done

**Comment by jbskolnik** [comment]
Can this link move to the teal footer to the right of "Cookies Policy", rather than in the list of "For Everyone"?  Thanks!

**Comment by SciStarter** [comment]
Done again
