### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#177]
In the login menu on the desktop version, pressing "enter" on the keyboard after writing the e-mail and password doesn't do anything, so I had to click on "Log in" using the mouse. Same thing when trying to log in via the SciStarter account, except that I got this message: "Can not log in to that account through SciStarter, because it was not created via SciStarter". Also, when logged-in on either desktop or mobile version, opening "https://sciencenearme.org/my/goals" and "https://sciencenearme.org/my/profile" in new tabs redirects to "https://sciencenearme.org/login?next=my-goals" and "https://sciencenearme.org/login?next=my-profile" respectively, thus prompting the login page again. However, that problem doesn't arise if I opened these same pages in the same tab.

**Comment by kevinripka-uiowa** [comment]
@SciStarter is there some reason you assigned this to me? Doesn't seem like a me issue.

**Comment by SciStarter** [comment]
@kevinripka-uiowa I was thinking the keyboard interaction was a you thing. Reassign it to me if you disagree.

**Comment by kevinripka-uiowa** [comment]
@SciStarter I fixed the enter thing by just wrpping in form element. But the other part about the new tabs and seeing the 'next' is probably yours.

**Comment by SciStarter** [comment]
The prompt for logins is a security precaution that we can't afford to skip, even though it's annoying.
