### ISSUE TITLE
Grammar mistakes

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#181]
_https://sciencenearme.org/about: "all types of  science" has 2 consecutive spaces; "supporting  academic researchers" has 2 consecutive spaces; "andThe Association" needs a space.
_https://sciencenearme.org/become-a-partner: "projects?  Become" has 2 consecutive spaces.
_https://sciencenearme.org/terms: the page is full of consecutive spaces, in pairs of 2, 3 or even 4 spaces next to each other; the comma in “Science Near Me,“ is misplaced; "ScienceNearMeaccount" needs a space; "non disclosure" needs a hyphen (-); "third party" should be hyphenated whenever it comes before the noun ("Third Party Intellectual Property", "third party websites", "third party information providers", "any such third party site"); the words "of" and "for" should not be capitalized in "Terms Of Use" and "Terms Of Service" and "Age Of User" and "Science For Citizens".
_https://sciencenearme.org/privacy: consecutive spaces are also present in pairs of 2, or 3 spaces next to each other; "provided )" and "www.scistarter.com ," should have the space removed; the word "for" should not be capitalized in "Protection For Children"; "ScienceNearMeUsers" and "ScienceNearMeaccordingly" and "ScienceNearMeand" need spacing; "third party service" needs a hyphen.
_https://sciencenearme.org/cookies: "websites.  ScienceNearMe" has consecutive spaces; "about theplatform" needs a space.
_https://sciencenearme.org/research-participant: "your area.  Any reports" has consecutive spaces; "organizations likeSciStarter" and "Center,COSI's" and "theAssociation" and "theScience" and "Alliance,The"  and "andDiscover" and "studies.This" and "Policyfor" need spacing.
_In some projects' individual pages, the comma in the project's location is appearing before the word rather than after it (e.g. ", Washington" instead of "Washington, "); some of these pages are:
https://sciencenearme.org/behavior-watch
https://sciencenearme.org/osprey-nestwatch---volunteer-monitoring-program
https://sciencenearme.org/-5-admission-after-4pm-2
https://sciencenearme.org/invent-a-holiday-ornament (this page only mentions the word "Visit", which doesn't make sense)
https://sciencenearme.org/lab-to-life-mystery-of-the-crooked-shell-gel-electrophoresis

**Comment by SciStarter** [comment]
Grammar mistakes in the content loaded from partners are not your problem, but you might want to fix the ones in the dynamic content.

**Comment by jbskolnik** [comment]
Fixed everything except on Research-Participant page cannot remove space between "Policyfor" in the "Your Information" section.  Looks totally different in the dynamic content editor (as did the space issue before as well, just had to play around with what worked).  Kevin I think it might be in the automatic formatting code for links? @kevinripka-uiowa
