### ISSUE TITLE
"Find Opportunities" section

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#182]
I browsed all 1964 projects in 197 pages on desktop (as many as I could find) in the "Find Opportunities" section (https://sciencenearme.org/find), and listed the below results (some projects should be deleted, others are duplicated, and others have issues with their logo):

_Projects which should be removed:
https://sciencenearme.org/test-create-project
https://sciencenearme.org/%EB%B3%84%EC%9D%B4-%EB%B9%9B%EB%82%98%EB%8A%94-eco-city
https://sciencenearme.org/chris-test

_Projects with no logo at all:
https://sciencenearme.org/test-bioactivity-javier
https://sciencenearme.org/natural-patterns-1
https://sciencenearme.org/restoration-of-native-plant-diversity-in-the-sonoran-desert
https://sciencenearme.org/butterflies-and-other-pollinators-of-the-crested-butte-wildflower-festival-1
https://sciencenearme.org/fastest-lift-1
https://sciencenearme.org/citizen-science-monitoring-for-long-island-eastern-box-turtles
https://sciencenearme.org/sas-monthly-general-meeting-4

_Duplicate projects and those which display ScienceNearMe's logo instead of the project host/provider's image (it makes the project headline less appealing to click):
https://sciencenearme.org/light-pollution-committee-meeting-2 (2 duplications)
https://sciencenearme.org/virtual-enrichment-classes-1
https://sciencenearme.org/bird-club (3 duplications)
https://sciencenearme.org/unc-greensboro-summer-tech-camps
https://sciencenearme.org/virtual-enrichment-classes-1
https://sciencenearme.org/boating-safety-certification (2 duplications)
https://sciencenearme.org/virtual-enrichment-classes-1
https://sciencenearme.org/star-party---garland-ranch-1
https://sciencenearme.org/bartlesville-astronomical-society-monthly-meeting-3
https://sciencenearme.org/cuyahoga-astonomical-association-lecture-and-meeting-2
https://sciencenearme.org/schools-out-camp-discovery-skin-and-bones
https://sciencenearme.org/stargazing-historic-canoa-ranch-1
https://sciencenearme.org/adios-to-dora-and-diego-lets-explore
https://sciencenearme.org/schools-out-camp-discovery-expedition-florida
https://sciencenearme.org/bartian-youth-astronomers-monthly-meeting-4
https://sciencenearme.org/scas-general-meetings
https://sciencenearme.org/say-cheese-celebrate-museum-selfie-day-at-mods
https://sciencenearme.org/starlight-astronomy-club-meeting
https://sciencenearme.org/pima-county-nrpr-star-party-tucson-mountain-park-ironwood-picnic-area-3
https://sciencenearme.org/planet-pioneers-overnight-camp-in
https://sciencenearme.org/schools-out-camp-discovery-planet-pioneers
https://sciencenearme.org/engineering-week
https://sciencenearme.org/24044
https://sciencenearme.org/kids-adventures-after-dark3
https://sciencenearme.org/planet-pioneers-journey-to-space
https://sciencenearme.org/dinosaurs-in-motion-overnight-camp-in
https://sciencenearme.org/kids-adventures-after-dark4
https://sciencenearme.org/2022sea-turtle-walks8
https://sciencenearme.org/kids-adventures-after-dark5
https://sciencenearme.org/kids-adventures-after-dark6
https://sciencenearme.org/kids-adventures-after-dark7
https://sciencenearme.org/lake-lowell-water-quality-1
https://sciencenearme.org/rephoto-kawuneeche-1
https://sciencenearme.org/off-the-roof---baltimore
https://sciencenearme.org/off-the-roof---tucson-1
https://sciencenearme.org/off-the-roof---miami-1
https://sciencenearme.org/downeast-maine-shellfish-sustainability-project
https://sciencenearme.org/maker-faire-tulsa
https://sciencenearme.org/kaboom-show8
https://sciencenearme.org/animal-encounters11
https://sciencenearme.org/animal-encounters10
https://sciencenearme.org/panther-prowl2
https://sciencenearme.org/mapping-coral-gables-1
https://sciencenearme.org/ccs-club-meeting-1
https://sciencenearme.org/aaap-monthly-club-meeting
https://sciencenearme.org/whac-club-meeting-virtual-1
https://sciencenearme.org/sfaa-january-virtual-meeting-1
https://sciencenearme.org/dlr-test-project
https://sciencenearme.org/remote-shoreline-debris-rapid-assessment-method

**Comment by SciStarter** [comment]
The issue tracker is not the appropriate place to address errors in the data.
