### ISSUE TITLE
Project-related false information

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#187]
The "World Community Grid" project is still listed on ScienceNearMe.org and SciStarter.org as hosted by IBM, while on September 13, 2021, it was announced that IBM has transferred the project's ownership to the Krembil Research Institute (https://www.worldcommunitygrid.org/about_us/article.s?articleId=732).

**Comment by SciStarter** [comment]
Another case of us receiving bad data. Nice catch, though, that's a subtle one.
