### ISSUE TITLE
Space needed between two ages in search bar

### ISSUE THREAD

**Issue by Ycitsci** [SciStarter/Circuit#19]
13. Can there be a bit of space between "12" and "21". Though it's quite understandable that the two ages should be close on the line, it may look confusing.
![13 age in advanced search](https://user-images.githubusercontent.com/92533858/137411430-3b830b0a-ffb1-4b4a-8c54-fcfec8583fc2.png)

**Comment by kevinripka-uiowa** [comment]
only way is to just make it start at 20. fixed in front-end-refactor
