### ISSUE TITLE
Page loading (according to Google's "Test My Site" tool)

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#191]
While I never had any issues regarding ScienceNearMe.org's loading speed, a quick test on Google's "Test My Site" tool gives it a poor rating: a screenshot from the report is attached, for more details.
![Google Test My Site report screenshot](https://user-images.githubusercontent.com/96191336/147279452-3f66ebe8-502a-4ec9-b103-d25e3e4a9741.png)

**Comment by SciStarter** [comment]
Google PageSpeed Insights lists 2 seconds loading time, and as you noted the real-world performance is fine.
