### ISSUE TITLE
Individual projects' pages

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#194]
In some project pages (e.g. https://sciencenearme.org/orca-project), the short summary right below the project's name and logo is nothing more than an incomprehensible duplication of the "More Information" paragraph in the same page, and that summary doesn't even provide a "read more" option, but instead, cuts the text right in the middle of the last word. In contrast, the summary on "https://sciencenearme.org/world-community-grid-1" is concise: "Support scientific research in health & sustainability.".

**Comment by SciStarter** [comment]
Unfortunately that's a problem in the data, not the site. I'll contact the partner about it, but I'm closing this.
