### ISSUE TITLE
Exif metadata

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#195]
The Exif metadata in some images on the site's homepage include personal names (check attachments):
Create or Build: the image authors field is "NASA/GSFC/Bill Hrybyk"
Make a Difference: the image authors and copyright fields is  "Emily Maletz"
![create-build 508a943](https://user-images.githubusercontent.com/96191336/147279601-e36e062b-ee4a-4b64-9e5e-257067eb6bc2.jpg)
![make-difference 53b5708](https://user-images.githubusercontent.com/96191336/147279604-97032f0f-6355-49bf-9b72-c518c922d0b5.jpg)

**Comment by SciStarter** [comment]
Not a concern, that's how the photographers chose to publish them.
