### ISSUE TITLE
ScienceNearMe → "Data Insights" issue (Date updated)

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#219]
"Date updated: 12/30/2022" is appearing across the "Data Insights" sub-pages: shouldn't the data update each time a user visits these pages?

**Comment by kevinripka-uiowa** [comment]
@ElMounRo it does not update each time. The data run is complex and so it is cached and pulled from that on a schedule. Not sure when the schedule is, but after confirming with @SciStarter I will add a 'updated every x' label.
