### ISSUE TITLE
ScienceNearMe → "Data Insights" issues ("Your Data Overview" sub-page)

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#220]
a. There's a naming discrepancy ("Your Data Overview" vs. "Data Overview") between the left column and the main content section.

b. Toggling between "Demo Partner" and "SciStarter" in the dropdown menu (as the organizations) doesn't update the on-page statistics.

c. After selecting "SciStarter" as the organization, the "Engagement", "Audience" and "Traffic" tabs stop working.

d. In the "Engagement" tab, after selecting the various "Opportunity Status" and "Time Period" value combinations a few times, the loading circle animation stops displaying, as if it stopped working.

e. In the "Audience" tab, the URL that's attached to "site-wide demographic data" is "https://beta.sciencenearme.org/", but shouldn't it be a more specific link?

f. Strange issue: after playing around in the "Engagement" tab then the "Audience" tab and changing the dropdown values within, I was no longer able to return to the former, but only managed to proceed to the "Traffic" tab, and then I could neither select the "Engagement" nor "Audience" tabs, until I left the whole "Data Insights" page and re-accessed it. As mentioned above, refreshing the page isn't an option ("Server error").

**Comment by kevinripka-uiowa** [comment]
I'll do a & e, @SciStarter b, c, f are yours

**Comment by SciStarter** [comment]
Sounds fair.

**Comment by kevinripka-uiowa** [comment]
My parts are done and in css-refine-12-22
