### ISSUE TITLE
ScienceNearMe → "Data Insights" issue ("Opportunity Data Explorer" sub-page)

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#222]
In the "Engagement Overlap" tab, I clicked through more than 100 projects in the dropdown list, but this tool doesn't seem to work because whichever project I selected, the stats always read "100% of users".

**Comment by SciStarter** [comment]
As expected. Hardly any users means even fewer crossovers, and there's some instrumentation that hasn't been deployed to the live site yet affecting this as well.
