### ISSUE TITLE
ScienceNearMe → generic issue (button text alignment)

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#224]
The text in the "Create Account" button isn't centered (Chrome on iPhone, portrait mode).

**Comment by kevinripka-uiowa** [comment]
@ElMounRo Can you clarify where this is or add pic? I don't see it. Header? Somewhere else? I'm also looking on chrome iphone portrait.

**Comment by ElMounRo** [comment]
I'm attaching 3 iOS screenshots, from Chrome and Safari and from ScienceNearMe.org and Beta.ScienceNearMe.org.

![3F285556-468D-4B79-BC67-BA75B336C88F](https://user-images.githubusercontent.com/96191336/211399063-94405bda-2b19-4ae3-8194-53f8f44de696.png)
![8F2AB7C6-CBB0-4F55-9194-171703766A36](https://user-images.githubusercontent.com/96191336/211399069-464e8911-85be-4871-a433-5155bb8a8d00.png)
![132CF486-161A-4BF7-B669-03560CA6A0F3](https://user-images.githubusercontent.com/96191336/211399075-53b3045a-2a84-4122-b329-31a5c7b115fd.png)

**Comment by kevinripka-uiowa** [comment]
fixed in branch css-refine-12-22
