### ISSUE TITLE
ScienceNearMe → generic issue ("My Activity Log" page)

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#227]
In the "My Activity Log" page (https://beta.sciencenearme.org/my/science), the "Report Your Science1" tab is missing a space before the number.

**Comment by kevinripka-uiowa** [comment]
That 1 should be styled as a notification...

**Comment by SciStarter** [comment]
And is, when I look at it...

**Comment by kevinripka-uiowa** [comment]
This was fixed in css-refine-12-22 but just never made it into master
