### ISSUE TITLE
ScienceNearMe → generic issue ("Your Partner Organization" page)

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#228]
In the "Your Partner Organization" page (https://beta.sciencenearme.org/my/organization), there are two duplicated dropdown menus to select the organization. This issue is only present on Beta.ScienceNearMe.org, not ScienceNearMe.org.

**Comment by kevinripka-uiowa** [comment]
@SciStarter I went to check this out and the first time I visited page, this didn't occur. Then I refreshed page and it did. Now it's always there. Is there some weird cache/cookie thing going on?

**Comment by SciStarter** [comment]
I believe that's what it is, yes.
