### ISSUE TITLE
Science Near Me: checklist related to topics

### ISSUE THREAD

**Issue by ElMounRo** [SciStarter/Circuit#229]
Is the checklist related to topics in the attached screenshot designed to look like this, or should it be like the one at the top of the page?
@kevinripka-uiowa 
![Screenshot](https://user-images.githubusercontent.com/96191336/217610930-44625ab0-370f-47de-8660-fc97b6e42dee.png)

**Comment by kevinripka-uiowa** [comment]
fixed in master
