### ISSUE TITLE
about "Science Goal" trophy threshold

### ISSUE THREAD

**Issue by Ycitsci** [SciStarter/Circuit#23]
17. This is about the threshold of getting a "science goal" trophy. The test account earned a goal of "Science Babbler" by clicking "I did This!" in five projects. It took about one minute. Was wondering if a little "challenge" can be added, for example, we can require users who want to progress towards a set "science goal" to at least add reviews besides clicking "I did This!". This should also hopefully promote the growth of project/event reviews and discussion.
![goal 1](https://user-images.githubusercontent.com/92533858/137411776-f831ed13-7aca-4c37-9069-dd4cd02a1313.png)
![goal 2](https://user-images.githubusercontent.com/92533858/137411784-efad8f4f-c65a-4d6f-a4a6-22d08bdfb14c.png)

**Comment by kevinripka-uiowa** [comment]
This is a temporary thing we're testing as self goals. It will like be completely rehauled in a future version. I'm actually just going to close this as we know it's in future work.
