### ISSUE TITLE
Your Overview - Audience Tab - Bar charts show other countries/cities but map is only US

### ISSUE THREAD

**Issue by kevinripka-uiowa** [SciStarter/Circuit#231]
Do we only want to show US States here since that is what is on the map?

<img width="385" alt="Screenshot 2023-05-30 at 4 12 59 PM" src="https://github.com/SciStarter/Circuit/assets/15911799/a7b14aa6-7895-4a79-a48c-aa7c3b09ffd0">

**Comment by SciStarter** [comment]
I think we should stick with the wider view here.
