### ISSUE TITLE
Your Overview - Traffic Tab - Viz for This Month maybe disable?

### ISSUE THREAD

**Issue by kevinripka-uiowa** [SciStarter/Circuit#232]
There seems to be no data for the "this month" selection of traffic data. Is this because the data only gets run once a month? Or is this just for now? We can remove "this month" if the data is not going to be pretty much daily.

<img width="717" alt="Screenshot 2023-05-30 at 4 16 04 PM" src="https://github.com/SciStarter/Circuit/assets/15911799/c02e866f-b3b5-46d9-843b-c8f82c3ad309">

**Comment by SciStarter** [comment]
It's because there actually was no data for that month at the time the data was collected (which was only the 2nd). If you can think of a good way of handling that, go for it.

**Comment by kevinripka-uiowa** [comment]
I've added a blank state message for when there is no data in a line chart. 
branch: data-ui-6-1-23
