### ISSUE TITLE
Opportunity Data Explorer - Engagement Tab - Inconsistent data of views

### ISSUE THREAD

**Issue by kevinripka-uiowa** [SciStarter/Circuit#234]
Using Alabama State Science and Engineering Fair (ASEF)

All time doesn't match up with this year and last year. Other dates seem oddly similar.

https://beta.sciencenearme.org/my/opportunity-data-explorer

**Comment by SciStarter** [comment]
Working on a fix.

**Comment by SciStarter** [comment]
Turns out this is because of having multiple, partial data runs in the database. Will resolve once we finally get to allow the collator to run to completion.
