### ISSUE TITLE
SNM Data Overview - Engagement Tab - Zero Unique Opportunity Page Views

### ISSUE THREAD

**Issue by kevinripka-uiowa** [SciStarter/Circuit#236]
Seems like no data. 

<img width="1190" alt="Screenshot 2023-05-30 at 5 10 01 PM" src="https://github.com/SciStarter/Circuit/assets/15911799/6316a98a-910d-445f-8de4-05a231824b2a">

**Comment by SciStarter** [comment]
Fix for this is on process.
