### ISSUE TITLE
SNM Data Overview - Traffic Tab - number of unique users and what is time period?

### ISSUE THREAD

**Issue by kevinripka-uiowa** [SciStarter/Circuit#240]
number of unique users is just showing a hex. And what is time period? Do we need a selector? 

https://beta.sciencenearme.org/my/snm-data-overview

<img width="1192" alt="Screenshot 2023-05-30 at 9 10 55 PM" src="https://github.com/SciStarter/Circuit/assets/15911799/d393be2b-bd75-4a8d-92d8-329d41ec2bda">

**Comment by SciStarter** [comment]
The time period is all time, always, and should remain so.

I've got a fix for the number in place, but it will take time for the correct number to show up here.
