### ISSUE TITLE
SNM Data Overview - Traffic Tab - Referrer Name not showing

### ISSUE THREAD

**Issue by kevinripka-uiowa** [SciStarter/Circuit#241]
The referrer name isn't showing. Also, we can fix the decimal of avg. time.

https://beta.sciencenearme.org/my/snm-data-overview

<img width="477" alt="Screenshot 2023-05-30 at 9 12 50 PM" src="https://github.com/SciStarter/Circuit/assets/15911799/a42e7cfb-97f5-49fc-af2b-5891aa24e254">

**Comment by SciStarter** [comment]
I'm going to remove that table. Those rows actually differ only by the referral source; all of the specific referrer data was blank. Browser security policy changes over the last couple of years have really cratered this data stream.
