### ISSUE TITLE
SNM Data Overview - Audience Tab - State Level data not showing

### ISSUE THREAD

**Issue by kevinripka-uiowa** [SciStarter/Circuit#244]
when you click on a state, there is no data shown.
<img width="1217" alt="Screenshot 2023-06-05 at 8 35 28 AM" src="https://github.com/SciStarter/Circuit/assets/15911799/2ce806d4-a167-41aa-b54f-1dc46f5f2c83">

**Comment by SciStarter** [comment]
Fixed now.
