### ISSUE TITLE
Start date not working

### ISSUE THREAD

**Issue by pbljenn** [SciStarter/Circuit#246]
I have an event that begins at 9:30am on 11/14 and ends at 2:30pm on 11/14. The form keeps telling me that my date fields have not been filled in and then defaults the start time to 12:00am on 11/14 and the end time to 2:30am on 11/14. Please help!

**Comment by pbljenn** [comment]
It appears that the only time that it will allow me to select as a start time on 11/14 is 12:00am. I need that start time to be accurate for this service to be useful.

**Comment by SciStarter** [comment]
Thank you for the report, we'll look in to it immediately.

**Comment by SciStarter** [comment]
Are you able to select the correct date and time if you select the date first, before selecting the time?

**Comment by SciStarter** [comment]
Closed for non-response, please feel free to re-open.
