### ISSUE TITLE
API doc and Display Science Opportunities links not working

### ISSUE THREAD

**Issue by Ycitsci** [SciStarter/Circuit#46]
R2-16. A potential partner of SNM or a potential opportunity provider can find links at the bottom of the webpage to proceed, but neither the "API documentation" link or "Display Science Opportunities" link work. Are they still under development?

![16 become a partner](https://user-images.githubusercontent.com/92533858/138376858-3a8969e8-b366-4689-8a84-0c86ac0401df.png)

**Comment by darcav1** [comment]
> 2\. Customize and Embed the Opportunity Finder”

Please have this link (footer section) direct to a "coming soon" page

**Comment by darcav1** [comment]
. Customize and Embed the Opportunity Finder”

Please have this link (footer section) direct to a "coming soon" page @SciStarter
