### ISSUE TITLE
SciStarter opps under In-Person Only?

### ISSUE THREAD

**Issue by jolenekg** [SciStarter/Circuit#67]
For example, when searching for In-Person opportunities in Hickory, NC, I'm seeing this global app listing as the first listing:

- https://scistarter.org/field-photo-library?utm_source=sciencenearme&utm_medium=web&utm_campaign=opp-page&utm_content=find-out-more

I'm not sure how "in-person" is defined. But even so, I would expect to see opportunities and events held at NC locations as the first listings. Right now there are only 2 that are showing on the first page of listings, the rest are all SciStarter opps that aren't even limited to NC or that region.

**Comment by SciStarter** [comment]
Those opportunities were 'in person or online' which are supposed to come up under a search for 'in person,'but they shouldn't come up ahead of nearby opportunities.
