### ISSUE TITLE
URL for record link less technical?

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#68]
I was confused by the full URL under "find out more" blue bar/button.  I don't think users need to see that full address.  Can we say instead, "Find out more about this oppotunity" without a URL?

Also the URL for this page's "Find out more" doesn't work for this record: https://beta.sciencenearme.org/moon-near-star-2
![Screenshot 2021-10-27 161911](https://user-images.githubusercontent.com/92173479/139141212-d6fac684-fc6d-480c-9f86-ab7b04400d92.png)

**Comment by kevinripka-uiowa** [comment]
removed in opportunity redesign
