### ISSUE TITLE
Record Order of sections

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#76]
The "About this Science Opportunity" seems buried in the record - you have to scroll a lot to get to it.  I'd recommend moving that higher, before More Information section.  Also maybe we need to say "STEM Opportunity" to be more inclusive to other areas besides science?

![Screenshot 2021-10-27 164318](https://user-images.githubusercontent.com/92173479/139144171-d2912dac-de91-4179-a103-abe25bb24dea.png)

**Comment by kevinripka-uiowa** [comment]
@jbskolnik  We already talked about this in design and the reason is that they should go to the website to read about it. Quick info on our site. It is now within the more info box.
