### ISSUE TITLE
Save button for account profile page?

### ISSUE THREAD

**Issue by jbskolnik** [SciStarter/Circuit#78]
I almost clicked "delete account" when trying to save the changes to the bottom items in my profile - looks like the natural place for "Save".  Can we add a Save button next to delete, or move delete to a less obvious place?
![Screenshot 2021-10-27 164715](https://user-images.githubusercontent.com/92173479/139144657-704e761d-1f0a-4ed6-a6b5-45a8071b93eb.png)

**Comment by kevinripka-uiowa** [comment]
@SciStarter can you put the same growl thing you put when someone likes. Maybe have it say: "saved"
