### ISSUE TITLE
opportunity page, "view map" doesn't appear to work

### ISSUE THREAD

**Issue by darcav1** [SciStarter/Circuit#80]
I see what might be an outline of a location but it's missing context or just isn't working.

**Comment by SciStarter** [comment]
Can you post a screenshot, and also a screenshot of your javascript console after you try viewing the map?

**Comment by SciStarter** [comment]
Clicked the wrong button there, didn't mean to close this yet.

**Comment by SciStarter** [comment]
Can't replicate the problem.
