### ISSUE TITLE
Some clicked links open new tab, some don't

### ISSUE THREAD

**Issue by kpreston21** [SciStarter/Circuit#84]
Just an observation that some links open a new tab e.g. Hosted by: MakerGirl (upper right) some lead directly to the new site in the same tab e.g. Register Now! (bottom left). (I am using chrome, on a laptop). Seems like opening a new tab would be preferable?
![image](https://user-images.githubusercontent.com/93331375/139274212-4c0baf18-7e42-4082-9347-99f0666ddd02.png)

**Comment by kevinripka-uiowa** [comment]
seems like they all open new tab if go to a different website.
