### ISSUE TITLE
Welcome [username]! pop up after logging in on mobile device?

### ISSUE THREAD

**Issue by kpreston21** [SciStarter/Circuit#89]
Just wondering if there could be some pop up or something of the like saying Welcome [username]!  or have the user name appear in the upper right hand corner near the magnifying glass when using a mobile device. When logged in on a computer, you can see your username in the upper right hand corner near the magnifying glass but on a mobile device your user name does not show up anywhere, even when you select the 'table of contents' icon in the upper left. I see it as a nice indicator that either you logged in successfully or perhaps are even already logged in. [please disregard any of my comments as you see fit]
![Screenshot_20211028-123751](https://user-images.githubusercontent.com/93331375/139298917-c7f46e01-e104-4a6e-9c61-5c0c618f021a.png)

**Comment by kevinripka-uiowa** [comment]
No real room and not totally necessary.
