### ISSUE TITLE
"see a map"

### ISSUE THREAD

**Issue by Ycitsci** [SciStarter/Circuit#9]
3. At an individual science project > see on map, the map is now showing up
![3 see on map](https://user-images.githubusercontent.com/92533858/137410337-73dfb006-f7f6-4da6-a698-410ae4b8ed4c.png)
.
![3 map](https://user-images.githubusercontent.com/92533858/137410363-ae3c9481-2169-4b75-90b5-388c7177ea34.png)

**Comment by kevinripka-uiowa** [comment]
@SciStarter originally this was just supposed to be a map in the right column for any non-online projects. With a polygon for an area location and a map marker for a location. No need for the map to be interactable, just a static. No see a map button.
